c = Category.create(name: 'Trade')
c.sub_categories.create(name: 'Furniture')
c.sub_categories.create(name: 'Book')
c = Category.create(name: 'People')
c.sub_categories.create(name: 'Travel Buddy')
c.sub_categories.create(name: 'Roommate')
c = Category.create(name: 'Lease')